version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/todo_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./drizzle:/app/drizzle
    command: >
      sh -c "npm run db:generate && npx ts-node -P tsconfig.migrate.json db/migrate.ts && node build/server.js"

volumes:
  postgres-data:
